theme: jekyll-theme-minimal
title: JYLiang的主页
data: 创建于2024/11/27
email: jyliang22@qq.com

description: 热爱技术的探索者
bio: 我是一个对技术充满热情的人，擅长[具体技术领域]，致力于[具体目标]。
occupation: 软件工程师
location: [具体地点]
social:
  twitter: [你的推特账号]
  linkedin: [你的领英账号]
  github: [你的 GitHub 账号]
image: /path/to/your/image.jpg
